[package]
name = "crabdrive-client"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true, features = ["serde"]}
console_error_panic_hook = { workspace = true }
icondata = {workspace = true}
formatx = { workspace = true }
leptos = { workspace = true, features = ["csr"] }
serde = { workspace = true, features = ["derive"]}
serde_json = { workspace = true }
thaw = { workspace = true, features = ["csr"] }
tracing-subscriber = { workspace = true }
tracing-web = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true, features = ["Request", "RequestInit", "RequestMode", "Response", "Window", "Blob", "SubtleCrypto", "Crypto", "CryptoKey", "AesGcmParams"] }

crabdrive-common = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
test-case = { workspace = true }
wasm-bindgen-test = { workspace = true }
