[package]
name = "crabdrive-client"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
console_error_panic_hook = { workspace = true }
leptos = { workspace = true, features = ["csr"] }
thaw = { workspace = true, features = ["csr"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-web = { workspace = true }

crabdrive-common = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
test-case = { workspace = true }
wasm-bindgen-test = { workspace = true }

