[package]
name = "crabdrive-client"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.8.3", features = ["csr"] }
thaw = { version = "0.5.0-beta", features = ["csr"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
tracing-web = "0.1.3"
