[package]
name = "crabdrive-common"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
pretty_assertions = "1.4.1"
test-case = "3.3.1"

[dependencies]
uuid = { version = "1.19.0", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
rusqlite = "0.29"
