[package]
name = "crabdrive-common"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
pretty_assertions = { workspace = true }
test-case = { workspace = true }

[dependencies]
uuid = { workspace = true }
serde = { workspace = true }
diesel = { workspace = true, features = ["sqlite"] }
